Algoritmo "Tipo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Robson
// Descrição   : uso de tipo
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27.02.2021

tipo
cadastro=registro
nome: caracter
idade: inteiro
salario: real
fimregistro

Var
// Seção de Declarações das variáveis 
cad: vetor[0..2] de cadastro
i,j: inteiro
resposta: caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo